# Generated by Django 4.1.7 on 2023-07-05 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='print_id',
            new_name='printer_id',
        ),
    ]
